### ISSUE TITLE
Review User API Endpoint Required Fields

### ISSUE THREAD

**Issue by dchukhin** [TransparentHealth/vmi#116]
Currently the following fields are required when creating a user through the user API endpoint:
 - `given_name`
 - `family_name`
 - `preferred_username`
 - `phone_number`
 - `gender`
 - `password`
 - `birthdate`
 - `nickname`
 - `email`

Could any of these be made optional?
Specifically, making some of these optional (like `gender`, `password`, `birthdate`, `nickname`, and `email`) could make user creation in the `smh_app` repo easier.

**Comment by aviars** [comment]
`preferred_username`
`given_name`
`family_name`
`gender`
`birthdate`
`password`

are required for `Member` accounts. Currently the API only supports creation of Member accounts (not Organizational Agent Accounts).
