### ISSUE TITLE
Profile images not displaying on alpha

### ISSUE THREAD

**Issue by aviars** [TransparentHealth/vmi#117]
the profile image returns 404. Perhaps the MEDIA_ROOT is set wrong in the environment,
<img width="1403" alt="Screen Shot 2019-05-10 at 9 01 46 AM" src="https://user-images.githubusercontent.com/61345/57529078-ddc27a80-72e8-11e9-9e75-ea60149b062c.png">

**Comment by whytheplatypus** [comment]
it looks like media_root was left in the local file-system.

What kind of setup would you like for file hosting? S3 is a standard safe bet.

**Comment by aviars** [comment]
S3 works.

**Comment by aviars** [comment]
fixed.
