### ISSUE TITLE
Terms of service - symbols from copy paste

### ISSUE THREAD

**Issue by philipcassidy** [TransparentHealth/vmi#180]
Location: Terms of service (http://sharemy.health/terms-of-service1.0.html)
Throughout the page, quotation marks and apostrophes are showing as symbols (probably from copy from Word).

![symbols from paste](https://user-images.githubusercontent.com/45177287/63356076-2b617100-c335-11e9-94d4-84c87542da72.png)
]()

**Comment by aviars** [comment]
Fixed.  Also URLs are now http://sharemy.health/terms-of-service-1.0.html and http://sharemy.health/privacy-policy-1.0.html
