### ISSUE TITLE
User and Member Profile: Upload Picture

### ISSUE THREAD

**Issue by philipcassidy** [TransparentHealth/vmi#181]
After selecting a file and clicking continue I get a site can’t be reached page. I attempted this with myself and two members

**Comment by philipcassidy** [comment]
UPDATE: I think this is a file sizing limit issue. I was able to upload a different image with lower quality.

**Comment by aviars** [comment]
@philipcassidy Do you have my email?

**Comment by aviars** [comment]
@philipcassidy can you connect with me on likedin?

**Comment by aviars** [comment]
@philipcassidy We now return a message saying the image is too large.  Please verify and reopen the issue if any issues.
