### ISSUE TITLE
Basic Profile Edit: UX Suggestions

### ISSUE THREAD

**Issue by philipcassidy** [TransparentHealth/vmi#183]
- After Editing a Basic Profile info item, the green confirmation message says “Pro settings have been updated.” From a UX perspective I think profile should be spelled out.

- After updating profile: From a UX perspective the Continue button is still available but does nothing but refresh the page.

**Comment by aviars** [comment]
@philipcassidy  Can you verify this has been fixed and/or attached a screen shot?

**Comment by aviars** [comment]
The typo was fixed. https://github.com/TransparentHealth/vmi/blob/d955a51d44cb9de906a64162c8e23e7d08003780/apps/accounts/views.py#L109
