### ISSUE TITLE
Provide CBO contact name for the organization

### ISSUE THREAD

**Issue by ManasiDutta** [TransparentHealth/vmi#195]
If a client is seeing more than one CBO, set each CBOs to see each other's contact person name, so they can contact them if needed.

**Comment by aviars** [comment]
Should only the point of contact be surfaced or all Agents for an org be listed?  I think the if part of the description can be removed.  When in the UI should Org this be surfaced?  Also a quick way to do this in the MVP would be to provide read-only access for Organization homepages.  Would this require a login?  Yes I think so, but we should elaborate this more.

**Comment by aviars** [comment]
The point of contact was added to the `id_token` so it become possible to display this in `smh_app`.

**Comment by aviars** [comment]
This information is passed in the id_token. Closing. Reopen if needed.
