### ISSUE TITLE
Add custom templates to Django OAuth Toolkit

### ISSUE THREAD

**Issue by aviars** [TransparentHealth/vmi#51]
Currently the screens for OAuth2 use the default templates and should instead extend from Base.html to match the rest of the site.  Also make these modifications:

* Do not allow a user to set his or her own application secret
* Ensure only one token exists per user per app.
* Only allow the confidential / authorization code flow.

Much of this can be copied over from the CMS BlueButton 2.0 project.

**Comment by whytheplatypus** [comment]
Why `Ensure only one token exists per user per app`?

**Comment by aviars** [comment]
Per the OAuth2 specification there is no requirement for one token per app/user, but its cleaner and simpler for people to understand.  Deleting the token deletes access.  I think its confusing for end users to have to understand they can delete a token for an app, but another one can remain.  We added this restriction in the BB API, and I recall its just a setting to Django OAuth Toolkit.  Your thoughts?

**Comment by whytheplatypus** [comment]
If it's a setting in oauth toolkit I'm all for turning it on, since it's easy to toggle, and seeing what people think.

In general while I completely agree that it's important to model that one to one grant of access between the user and the application once an application has reached a certain size. Access tokens can become a messy way to do it.

**Comment by aviars** [comment]
Here is where this is activated in BB 2.0. I see its not a seeing but a custom validator.  The

https://github.com/TransparentHealth/bluebutton-web-server/blob/69b6e649b2e9caf7859a75ea3867bf74c83ca340/hhs_oauth_server/settings/base.py#L280

https://github.com/TransparentHealth/bluebutton-web-server/blob/develop/apps/dot_ext/oauth2_validators.py

**Comment by aviars** [comment]
@whytheplatypus Mind if I take this one on?

**Comment by aviars** [comment]
This should really be split into multiples?

**Comment by aviars** [comment]
Done.  Consider moving same logic into SMH.
