### ISSUE TITLE
FIDO

### ISSUE THREAD

**Issue by aviars** [TransparentHealth/vmi#52]
After attempting to delete the FIDO credential using the admin, alpha now returns

`AttestedCredentialData matching query does not exist.`  It appears to be coming from the middleware.  We want to be able to remove credentials from the admin.  If the admin delete works, I can build out the main UI to allow the removal of the token.

**Comment by whytheplatypus** [comment]
The session probably needs the ability to recover after the credential currently stored in it is removed.
