### ISSUE TITLE
Cannot submit a mobile phone number

### ISSUE THREAD

**Issue by whytheplatypus** [TransparentHealth/vmi#65]
Cannot submit a phone number from https://alpha.verifymyidentity.com/accounts/mobile-phone with "Verify now" unselected.

Results in a `KeyError` due to the `phone_verified` field not being returned at all to the server. This is likely because unchecked checkboxes in forms are often excluded in the POST request a server.

**Comment by whytheplatypus** [comment]
This doesn't work with "Verify now" selected either.

**Comment by aviars** [comment]
Lets review. Not sure if I have it.

**Comment by whytheplatypus** [comment]
fixed by #73 


https://github.com/TransparentHealth/vmi/commit/ef79198953aa2563faa1cd122dbf61417ec38161#diff-c2016e6e664b3896f66f82f3aed87f38R77
