### ISSUE TITLE
404 from "Add New Identifier" button on Identifiers page

### ISSUE THREAD

**Issue by whytheplatypus** [TransparentHealth/vmi#67]
https://alpha.verifymyidentity.com/accounts/individual-identifiers/

**Comment by aviars** [comment]
@whytheplatypus This is because your user doesn't have permission to do this action.  Perhaps what is needed here is a way to assign user's into groups w/o using the Django admin?

**Comment by whytheplatypus** [comment]
I think it's fine that they don't have permissions, the button should just be conditionally removed then if they can't get to that page.

**Comment by aviars** [comment]
Fixed some time ago. :-)
