### ISSUE TITLE
Account CRUD through RESTful API

### ISSUE THREAD

**Issue by aviars** [TransparentHealth/vmi#96]
Add API to allow account user creation, identifiers, addresses, and IAL.

**Comment by whytheplatypus** [comment]
requires a token from a logged in user with the appropriate permissions.

**Comment by whytheplatypus** [comment]
Results in an Account without credentials, and some event triggered to enable the correct parties to set credentials.

**Comment by whytheplatypus** [comment]
Create a User Example #2 - More Options
========================================

The following example illustrates an account creation with more demographic and identity infiormation.


* HTTP Method: POST 
* Request Body: application/json
* Response Body: application/json
* Endpoint:https://alpha.verifymyidentity.com/api/v1/user/
* Authorization: OAuth2 Bearer Token



Request Body
------------

    {
  	"iss": "https://alpha.verifymyidentity.com",
    "subject": "123456789012345",  
    "preferred_username": "james",
    "given_name": "James",
    "family_name": "Kirk",
    "gender": "male",
    "password": "tree garden jump fox,
    "birthdate": "1952-01-03",
    "nickname": "Jim",
    "phone_number": "+15182345678",
    "email": "jamess@example.com"
    }



Successful Request Response
---------------------------

A successful response `HTTP 200`:


    {
    "iss": "https://alpha.verifymyidentity.com",
    "subject": "123456789012345", 
    "preferred_username": "james",
    "given_name": "James",
    "family_name": "Kirk",
    "name": "James Kirk",
    "gender": "male",
    "birthdate": "1952-01-03",
    "nickname": "Jim",
    "phone_number": "+15182345678",
    "email": "jamess@example.com",
    "ial": 1,
    "id_assursance" : [],
    "document" : [],
    "address": []
    }



Modify a User's Date of Birth
------------------------------

* HTTP Method: POST or PUT
* Request Body: application/json
* Response Body: application/json
* Endpoint: https://alpha.verifymyidentity.com/api/v1/user/[sub]
* Authorization: OAuth2 Bearer Token


Request Endpoint: HTTP PUT /api/v1/user/123456789012345

Request Body:
-------------


    {
    "birthdate": "2233-03-22"
    }



Successful Response
-------------------

Response code is `200`. 


    {
    "sub": "123456789012345",
    "birthdate": "2233-03-22"
    }
